### ISSUE TITLE
Using the trained model

### ISSUE THREAD

**Issue by ShivanshuPurohit** [pbloem/former#14]
How do I use the trained model to generate text?

**Comment by pbloem** [comment]
The script currently doesn't allow saving and loading. See https://pytorch.org/tutorials/beginner/saving_loading_models.html for instructions on how to add this. 

[These lines](https://github.com/pbloem/former/blob/6a3295c94a151291de6838b98826da13e5f57bf3/experiments/generate.py#L170-L193) are responsible for generating some text from the model. You can adapt those as necessary. Text generation happens in batches so you may need to stare at the code for a bit to see how it works.
