### ISSUE TITLE
slide 50, v and q mixed up

### ISSUE THREAD

**Issue by ulf1** [pbloem/former#19]
where? slide 50, https://dlvu.github.io/slides/dlvu.lecture12.pdf

typo: the `v` and `q` input variables of source-attention layer are wrong. 

_"... In "encoder-decoder attention" layers, **the queries come from the previous decoder layer**,and the memory keys and values come from the output of the encoder..."_ (Vaswani et al, 2007, p.5)

**Comment by pbloem** [comment]
Ah, thanks. I'll fix it when I get a chance.
