### ISSUE TITLE
Weight scaling should be for keys not values?

### ISSUE THREAD

**Issue by esvhd** [pbloem/former#2]
Hi @pbloem ,

Thanks for the great post. Best I've read on this topic. 

Reading through the code, when performing weight scaling, I wonder whether the line here should be scaling `keys` not `values`?

https://github.com/pbloem/former/blob/2077d00f45fca9e5e31da036278fe65bd0cbc47f/former/modules.py#L48-L49

A couple of lines down from here we have 

https://github.com/pbloem/former/blob/2077d00f45fca9e5e31da036278fe65bd0cbc47f/former/modules.py#L54

Best.

**Comment by pbloem** [comment]
You're totally right. This was a last minute change, and I guess I wasn't paying attention. I've also added a note to the blog post, explaining where this comes from.

**Comment by esvhd** [comment]
Actually I only noticed this because the great blog post you wrote and the comments. Thank you for the great work!
