### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by RubenRidderstrom** [pbloem/former#24]
Hi @pbloem,
Thank you for a great blog post. Running

`python experiments/classify.py`

on my regular conda environment gives the output

```
(MyDeeplearningEnv) PS C:\Users\Ruben\Desktop\former> python experiments/classify.py
Traceback (most recent call last):
  File "experiments/classify.py", line 1, in <module>
    from _context import former
  File "C:\Users\Ruben\Desktop\former\experiments\_context.py", line 7, in <module>
    import former
  File "C:\Users\Ruben\Desktop\former\former\__init__.py", line 1, in <module>
    from .modules import SelfAttention, SelfAttentionWide, TransformerBlock, SelfAttentionRelative, SelfAttentionNarrow
  File "C:\Users\Ruben\Desktop\former\former\modules.py", line 1, in <module>
    from former import util
  File "C:\Users\Ruben\Desktop\former\former\util\__init__.py", line 1, in <module>
    from .util import mask_, d, here, contains_nan, tic, toc, \
  File "C:\Users\Ruben\Desktop\former\former\util\util.py", line 6, in <module>
    import transformers as trf
  File "C:\Users\Ruben\Desktop\former\former\transformers.py", line 5, in <module>
    from .modules import TransformerBlock
ImportError: attempted relative import with no known parent package
```

I tried creating a clean environment using
```
pip install torch tb-nightly tqdm numpy torchtext
pip install future
```
This resulted in more fstring errors which I removed and then got the same error as above. Creating a environment from the environment.yml fails to resolve. 

Any helps is appreciated.

**Comment by pbloem** [comment]
If you're getting fstring errors, it sounds like you're using an old version of python. Could you try creating a conda environemnt with python v3.6 or higher?

**Comment by RubenRidderstrom** [comment]
If I use Python 3.8.10 I only get the ImportError. With any lower version of Python I also get fstring errors in addition to the ImportError.

**Comment by pbloem** [comment]
There's a slight hack in the experiments to avoid having to install the package. Could you try running:

```pip install -e .```

in the directory that contains setup.py? That might fix the problem.

**Comment by RubenRidderstrom** [comment]
Unfortunately it made no difference, still get the same error.

**Comment by pbloem** [comment]
Looks like it's related to this: https://stackoverflow.com/questions/16981921/relative-imports-in-python-3 

Basically, van Rossum considers packaging scripts together with code like I've done here an antipattern, so it's poorly supported. You could try running: 
```
python -m experiments/classify.py
```

I think a more robust solution is probably to remove the relative import hack and require package installation. I'll implement that when I get some time.

**Comment by RubenRidderstrom** [comment]
Running that returns "Relative module names not support". Thanks anyway for trying. Having access to the code is still of great help.

**Comment by pbloem** [comment]
I went though all the code to ensure that it runs from a clean conda environment with python 3.6. Turns out that quite a few issues had crept in, but it now works for me.

 Could you try again with a clean 3.6 environment and the updated instructions, to see if it works?

**Comment by RubenRidderstrom** [comment]
That works perfectly. Only had to run "pip install -e ." in a clean 3.6 environment.
