### ISSUE TITLE
Masking done for the upper or lower triangle?

### ISSUE THREAD

**Issue by esvhd** [pbloem/former#6]
Hi,

I believe the comment should be masking the **upper** not the lower triangle of the matrix? Both the blog and the code referred to the upper half of the matrix.

Thanks.

https://github.com/pbloem/former/blob/7b12ae6025cb5797c7ce95750c9777eb2130ba25/former/modules.py#L58-L59

**Comment by pbloem** [comment]
Thanks for the pointer. You're totally right. The masking also excluded the diagonal in the current implementation. Should be fixed now.
